### ISSUE TITLE
Upgrade dev and global gulp 3.9.1 to 4.0.0

### ISSUE THREAD

**Issue by ryahconstantino** [ryahconstantino/htmlworkflow#1]
**DEPRECATED GULP**
==============
- **gulpfile.js**
The code needs to be updated to 4.0.0

Following WARNS from npm:
- natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.

- minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

- graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

**Comment by ryahpalma** [comment]
Code was successfully updated to gulp 4.0.0

**Comment by ryahconstantino** [comment]
Code was successfully updated to gulp 4.0.0
